<<<<<<< HEAD
---
title: "Data Collection"
author: "Ellen Graham"
date: "November 4, 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(readr)
library(dplyr)
library(ggplot2)
library(knitr)
library(broom)
```



Gapminder data
```{r}
library(tidyr)

filenames <- list.files(path="GapMinderData",pattern="*.csv", full.names=TRUE)
contraceptive<-read_csv(filenames[[1]])

nchar(filenames[[1]])

(name<-substring(filenames[[1]], 15, nchar(filenames[[1]])-4))
contraceptive<-contraceptive %>% 
   gather(key=year, value=temp, 2:length(contraceptive))
colnames(contraceptive)[1]<-"country"
colnames(contraceptive)[3]<-name
contraceptive[contraceptive == 0] <- NA
head(contraceptive)
```

```{r}
makeGapMinderTable<-function(file_path){
   table<-read_csv(file_path)
   name<-substring(file_path, 15, nchar(file_path)-4)
   table<-table %>% 
      gather(key=year, value=temp, 2:length(table))
   table
   colnames(table)[1]<-"country"
   colnames(table)[3]<-name
   table[table == 0] <- NA
   table
}
```

```{r}
allGapminderTables<-lapply(filenames, makeGapMinderTable)
```



```{r}
joined_Gapminder_tables<-allGapminderTables[[1]]
for(i in 2:length(allGapminderTables)){
      joined_Gapminder_tables<-full_join(joined_Gapminder_tables, allGapminderTables[[i]], by=c("country", "year"))
}

joined_Gapminder_tables<-joined_Gapminder_tables %>% 
   select(-age_at_1st_marriage_women)

dim(joined_Gapminder_tables)
na_free_table<-na.omit(joined_Gapminder_tables)

```

```{r}
kable(table(na_free_table$country))
kable(table(na_free_table$year))

```





```{r}
head(na_free_table)
names(joined_Gapminder_tables)
```

```{r}
#alldata.lm<-joined_Gapminder_tables %>% lm(life_expectancy_female~contraceptive_use_percent_of_women_ages_15_49+
                     #females_aged_15plus_unemployment_rate_percent+
                     #mean_years_in_school_women_percent_men_25_to_34_years+
                     #ratio_of_girls_to_boys_in_primary_and_secondary_education_perc+country, data=.)


```

#Visualizations of Data

##Colored by year
```{r}
class(joined_Gapminder_tables$year)

joined_Gapminder_tables %>%
   group_by(year) %>% 
   filter(n()>5) %>% 
   ggplot()+
   geom_point(aes(x=contraceptive_use_percent_of_women_ages_15_49, y=life_expectancy_female, color=as.numeric(year)))+
   scale_color_gradient(limits=c(1970, 2015))+
   geom_smooth(data=joined_Gapminder_tables, aes(x=contraceptive_use_percent_of_women_ages_15_49, y=life_expectancy_female, fill=year), method="lm", se=FALSE)+
   theme(legend.position="none")
```

```{r}
alldata.lm<-joined_Gapminder_tables %>% 
   group_by(year) %>% 
   filter(n()>5) %>% 
   lm(life_expectancy_female~contraceptive_use_percent_of_women_ages_15_49*year, data=.)

tidy(summary(alldata.lm))
```

```{r}
joined_Gapminder_tables %>%
   group_by(year) %>% 
   filter(n()>5) %>% 
   ggplot(aes(x=females_aged_15plus_unemployment_rate_percent, y=life_expectancy_female, color=year))+
   geom_point()+
   geom_smooth(method="lm")+
   theme(legend.position="none")

#change
```

```{r}
joined_Gapminder_tables %>%
   group_by(year) %>% 
   filter(n()>5) %>% 
   ggplot(aes(x=males_aged_15plus_unemployment_rate_percent, y=life_expectancy_female, color=year))+
   geom_point()+
   geom_smooth(method="lm")+
   theme(legend.position="none")

#change
```

```{r}
joined_Gapminder_tables %>%
   group_by(year) %>% 
   filter(n()>5, females_aged_15plus_unemployment_rate_percent/males_aged_15plus_unemployment_rate_percent<20) %>% 
   ggplot(aes(x=females_aged_15plus_unemployment_rate_percent/males_aged_15plus_unemployment_rate_percent, y=life_expectancy_female, color=year))+
   geom_point()+
   geom_smooth(method="lm")+
   theme(legend.position="none")

#change
```

```{r}
joined_Gapminder_tables %>%
   group_by(year) %>% 
   filter(n()>5) %>% 
   ggplot(aes(x=mean_years_in_school_women_percent_men_25_to_34_years, y=life_expectancy_female, color=year))+
   geom_point()+
   geom_smooth(method="lm")+
   theme(legend.position="none")

```

```{r}
joined_Gapminder_tables %>%
   group_by(year) %>% 
   filter(n()>5) %>% 
   ggplot(aes(x=ratio_of_girls_to_boys_in_primary_and_secondary_education_perc, y=life_expectancy_female, color=year))+
   geom_point()+
   geom_smooth(method="lm")

```

##Colored by country
```{r}
joined_Gapminder_tables %>%
   group_by(year) %>% 
   filter(n()>5) %>% 
   ggplot(aes(x=contraceptive_use_percent_of_women_ages_15_49, y=life_expectancy_female, color=country))+
   geom_point()+
   geom_smooth(method="lm")+
   theme(legend.position="none")

#change
```

```{r}
joined_Gapminder_tables %>%
   group_by(year) %>% 
   filter(n()>5) %>% 
   ggplot(aes(x=females_aged_15plus_unemployment_rate_percent, y=life_expectancy_female, color=country))+
   geom_point()+
   geom_smooth(method="lm")+
   theme(legend.position="none")

#change
```

```{r}
joined_Gapminder_tables %>%
   group_by(year) %>% 
   filter(n()>5) %>% 
   ggplot(aes(x=males_aged_15plus_unemployment_rate_percent, y=life_expectancy_female, color=country))+
   geom_point()+
   geom_smooth(method="lm")+
   theme(legend.position="none")

#change
```

```{r}
joined_Gapminder_tables %>%
   group_by(year) %>% 
   filter(n()>5, females_aged_15plus_unemployment_rate_percent/males_aged_15plus_unemployment_rate_percent<20) %>% 
   ggplot(aes(x=females_aged_15plus_unemployment_rate_percent/males_aged_15plus_unemployment_rate_percent, y=life_expectancy_female, color=country))+
   geom_point()+
   geom_smooth(method="lm")+
   theme(legend.position="none")

#change
```

```{r}
joined_Gapminder_tables %>%
   group_by(year) %>% 
   filter(n()>5) %>% 
   ggplot(aes(x=mean_years_in_school_women_percent_men_25_to_34_years, y=life_expectancy_female, color=country))+
   geom_point()+
   geom_smooth(method="lm")+
   theme(legend.position="none")

```

```{r}
joined_Gapminder_tables %>%
   group_by(year) %>% 
   filter(n()>5) %>% 
   ggplot(aes(x=ratio_of_girls_to_boys_in_primary_and_secondary_education_perc, y=life_expectancy_female, color=country))+
   geom_point()+
   geom_smooth(method="lm")+
   theme(legend.position="none")

```




>>>>>>> 61ccb208c38d46cbf9e958e2c74d333c93b25f2c
